# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ratizux
name: Blockcity
email: nebclllo0444@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blockcity 使用 Jekyll 搭建的博客<br/>使用 CC BY-SA 4.0
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ratizux.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  Ratizux

# Build settings
markdown: kramdown
